CREATE DATABASE GymDB;
USE GymDB;
CREATE TABLE MembershipPlans(
PlanID INT PRIMARY KEY AUTO_INCREMENT,
PlanName VARCHAR(50) UNIQUE NOT NULL,
Price DECIMAL(10,2) NOT NULL,
DurationMonths INT NOT NULL,
Benefits TEXT
); 

CREATE TABLE Members(
MemberID INT PRIMARY KEY AUTO_INCREMENT,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Email VARCHAR(100) UNIQUE NOT NULL,
Phone VARCHAR(20),
Address VARCHAR(255),
DateOfBirth DATE,
PlanID INT NOT NULL,
MembershipStartDate DATE NOT NULL,
MembershipEndDate DATE,
OustandingBalance DECIMAL(10,2) DEFAULT(0.00),
CONSTRAINT FK_Members_PlanID FOREIGN KEY (PlanID) REFERENCES MembershipPlans(PlanID)
);

CREATE TABLE Trainers(
TrainerID INT PRIMARY KEY AUTO_INCREMENT,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Email VARCHAR(100) UNIQUE NOT NULL,
Phone VARCHAR(20),
Specialisation VARCHAR(100)
);

CREATE TABLE Classes(
ClassID INT PRIMARY KEY AUTO_INCREMENT,
ClassName VARCHAR(100) NOT NULL,
ClassDescription TEXT,
ClassDate DATE NOT NULL,
StartTime TIME NOT NULL,
EndTime TIME NOT NULL,
TrainerID INT NOT NULL,
MaxCapacity INT NOT NULL,
CurrectBookings INT DEFAULT(0),
CONSTRAINT FK_Classes_TrainerID FOREIGN KEY (TrainerID) REFERENCES Trainers(TrainerID)
);

CREATE TABLE Bookings(
BookingID INT PRIMARY KEY NOT NULL,
MemberID INT NOT NULL,
ClassID INT NOT NULL,
BookingDateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
BookingStatus ENUM('Confirmed', 'Pending', 'Cancelled', 'Completed') NOT NULL,
Attendance BOOLEAN DEFAULT(false),
CONSTRAINT FK_Bookings_MemberID FOREIGN KEY (MemberID) REFERENCES Members(MemberID),
CONSTRAINT FK_Bookings_ClassID FOREIGN KEY (ClassID) REFERENCES Classes(ClassID)
);

CREATE TABLE Payments(
PaymentID INT PRIMARY KEY AUTO_INCREMENT,
MemberID INT NOT NULL,
Amount DECIMAL(10,2) NOT NULL,
PaymentDate DATE NOT NULL DEFAULT (CURRENT_DATE),
PaymentMethod VARCHAR(50),
PaymentDescription VARCHAR(255),
TransactionReference VARCHAR(100) UNIQUE,
CONSTRAINT FK_Payments_MemberID FOREIGN KEY (MemberID) REFERENCES Members(MemberID)
);