CREATE DATABASE GymDB;
USE GymDB;
CREATE TABLE MembershipPlans(
PlanID INT PRIMARY KEY AUTO_INCREMENT,
PlanName VARCHAR(50) UNIQUE NOT NULL,
Price DECIMAL(10,2) NOT NULL,
DurationMonths INT NOT NULL,
Benefits TEXT
); 